### ISSUE TITLE
[BUG] Global context configuration not working properly

### ISSUE THREAD

**Issue by MatheusPoliCamilo** [zormandi/logcraft#1]
## Description

Trying to set the `global_context` configuration with the **environment**, in a **new Rails application**, but isn't working.

## How Has This Been Tested?

Used this code in the `config/environments/development.rb`:
```
config.logcraft.global_context = -> do
  {
    environment: ENV['RAILS_ENV']
  }
end
```

But the log accessing the `http://localhost:3000/` is not adding the **environment**:

```
{"timestamp":"2022-07-15T17:07:16.425-03:00","level":"INFO","logger":"AccessLog","hostname":"DESKTOP-JBFF1SI","pid":383,"message":"GET / - 200 (OK)","remote_ip":"::1","method":"GET","path":"/","params":{"controller":"rails/welcome","action":"index"},"response_status_code":200,"duration":127,"duration_sec":0.127}
```

### Workaround

Using the configuration above in the `config/environments/development.rb`, everything works fine:

```
Logcraft.add_to_log_context({
  environment: ENV["RAILS_ENV"]
})
```

The log it generates accessing the `http://localhost:3000/`:

```
{"timestamp":"2022-07-15T17:36:52.884-03:00","level":"INFO","logger":"AccessLog","hostname":"DESKTOP-JBFF1SI","pid":5678,"environment":"development","message":"GET / - 304 (Not Modified)","remote_ip":"::1","method":"GET","path":"/","params":{"controller":"rails/welcome","action":"index"},"response_status_code":304,"duration":71,"duration_sec":0.071}
```

## Versions

- Ruby 3.0.3
- Rails 7.0.3.1
- Logcraft 1.0.0.rc

**Comment by zormandi** [comment]
Hi @MatheusPoliCamilo,

The reason why setting the global context to a lambda isn't working is that it wasn't supported in the 1.0.0.rc version. If you look at the documentation for the RC then you'll see that it must be set to a Hash (which may contain lambdas): https://github.com/zormandi/logcraft/tree/v1.0.0.rc . The reason I decided to change it for the main release is that with the RC version of this feature there was no way to not provide certain keys in the context if they weren't necessary, which makes sense e.g. for the DataDog integration. Having the global context be a lambda provides much more flexibility.

So this should work fine:
```ruby
config.logcraft.global_context = {
    environment: ENV['RAILS_ENV']
}
```

As for how this feature was tested, if you check the code you'll see that it has both unit and integration tests... although I suspect that was more of a rhetorical question.

Sorry about the confusion.

**Comment by MatheusPoliCamilo** [comment]
Just changed to `global_context` instead of `initial_context` and everything worked fine, thank you very much!

**Comment by zormandi** [comment]
I assume you've changed to the main branch then (soon to be released). So just to be clear `initial_context` in the RC version, `global_context` on the main branch.
