### ISSUE TITLE
Conditionally disable Logcraft w/ Rails

### ISSUE THREAD

**Issue by kphan32** [zormandi/logcraft#4]
In a Rails project, is there a way to disable Logcraft conditionally? Would love to use Logcraft in prod environments, but for local development I'd prefer the default Rails logger.

**Comment by zormandi** [comment]
No, not really. To be honest, I haven't considered wanting to see different logs in development and production so there isn't an easy mechanism for switching. You would basically have to revert the setup that's in the `railtie.rb`.

Do you want to switch because of the readability or are you missing data (e.g. view render time). If it's just about the format then you can use the `logcraft.layout_options.formatter` configuration option to output nicer looking messages specifically in the development environment.

**Comment by kphan32** [comment]
It was mainly for readability, but I ended up doing what you suggested and formatted the logs to look about the same. Also needed to mute the `SQL SCHEMA` events-- those don't seem to appear in Rails's default logging. Thanks!

**Comment by incubus** [comment]
@kphan32 could you please share your formatter? Thank you!

**Comment by kphan32** [comment]
```
# Adjust Logcraft verbosity by environment.
module LogVerbosity
  module ByEnvironment
    private

    def background_of(event)
      super.slice(*context_filter)
    end

    def context_filter
      @context_filter ||= case Rails.env
                          when "production", "staging"
                            %w[timestamp level dd]
                          when "development", "test"
                            %w[level]
                          end
    end
  end
end

Logcraft::LogLayout.prepend(LogVerbosity::ByEnvironment)
```

**Comment by g-pavlik** [comment]
Chiming in on the issue. It is possible to conditionally enable `logcraft`, and it's fairly easy: 
```
# Gemfile
gem "logcraft", require: false
```
and then 
```
$ config/application.rb
unless ENV.fetch("DISABLE_LOGCRAFT", false) == "true" 
  require "logcraft"
end

module MyApp
  class Application << Rails::Application 
    # ...
    if config.respond_to?(:logcraft) 
     config.logcraft...
   end
end
```

Why? I, personally, want to do it only in a single place: local console. As much as I love what `logcraft` does – loosing this nicely colored coloring in the console is something I despise. 

@zormandi would that be something that fit into the README? I could handle the PR if yes.

**Comment by zormandi** [comment]
@g-pavlik, that would be amazing. Thank you.
