### ISSUE TITLE
NoMethodError: undefined method `formatter='

### ISSUE THREAD

**Issue by mhenrixon** [zormandi/logcraft#5]
https://github.com/TwP/logging/issues/245 

Crossposting in case you depend on twp/logging and need a version bump or something.

**Comment by zormandi** [comment]
Thanks, I'll look into it. 👍

**Comment by brandondrew** [comment]
I'm getting the error with Rails 7.0.7.2:

```
 undefined method `formatter=' for #<Logging::Logger:0x0000000123555d38 @name="Application", @parent=#<Logging::RootLogger:0x0000000117f18c50 @name="root", @appenders=[#<Logging::Appenders::Stdout:0x00000001229fed90 @io=#<IO:<STDOUT>>, @close_method=:close, @buffer=[], @immediate=[], @auto_flushing=1, @async=false, @async_flusher=nil, @flush_period=nil, @name="stdout", @closed=false, @filters=[], @mutex=#<ReentrantMutex:0x00000001229da878 @locker=nil>, @layout=#<Logcraft::LogLayout:0x00000001229bb8b0 @global_context={}, @formatter=#<Proc:0x0000000121a33e60 /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/logcraft-2.1/lib/logcraft/log_layout.rb:7 (lambda)>, @level_formatter=#<Proc:0x0000000121a33de8 /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/logcraft-2.1/lib/logcraft/log_layout.rb:8 (lambda)>>, @level=0, @encoding=#<Encoding:UTF-8>, @write_size=500>], @additive=false, @caller_tracing=false, @level=1>, @appenders=[], @additive=true, @level=1, @caller_tracing=false> (NoMethodError)

        logger.formatter = ActiveSupport::Logger::SimpleFormatter.new
              ^^^^^^^^^^^^
```

**Comment by zormandi** [comment]
@brandondrew I couldn't reproduce the issue with Rails 7.0.7.2. All tests run fine. Unless, of course, you're calling `logger.formatter = ...` explicitly, which you shouldn't do. If this is in a newly generated Rails configuration then you should remove those lines.

**Comment by zormandi** [comment]
New version is released which fixes compatibility issues with Rails 7.1.

**Comment by mhenrixon** [comment]
Thank you! I'll give it a spin later today.

**Comment by lauer** [comment]
It seems like I have the same bug in Rails 7.1.3, after I start to use broadcast/hotwire, or maybe I have misconfigured something?

16:05:23 web.1  | /Users/jesper.laursen/.dotfiles/link/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/broadcast_logger.rb:146:in `block in formatter=': undefined method `formatter=' for #<Logging::Logger:0x0000000114892be0 @name="Application", @parent=#<Logging::RootLogger:0x0000000114817620 @name="root", @appenders=[#<Logging::Appenders::Stdout:0x0000000113698840 @io=#<IO:<STDOUT>>, @close_method=:close, @buffer=[], @immediate=[], @auto_flushing=1, @async=false, @async_flusher=nil, @flush_period=nil, @name="stdout", @closed=false, @filters=[], @mutex=#<ReentrantMutex:0x0000000113698340 @locker=nil>, @layout=#<Logcraft::LogLayout:0x000000011489a570 @global_context={}, @formatter=#<Proc:0x0000000113698cf0 /Users/jesper.laursen/.dotfiles/link/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/logcraft-2.2.1/lib/logcraft/log_layout.rb:7 (lambda)>, @level_formatter=#<Proc:0x0000000113698c78 /Users/jesper.laursen/.dotfiles/link/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/logcraft-2.2.1/lib/logcraft/log_layout.rb:8 (lambda)>>, @level=0, @encoding=#<Encoding:UTF-8>, @write_size=500>], @additive=false, @caller_tracing=false, @level=1>, @appenders=[], @additive=true, @level=1, @caller_tracing=false, @logdev=#<OpenStruct dev=#<IO:<STDOUT>>>> (NoMethodError)

**Comment by juna-nb** [comment]
@lauer this change (yet un-merged) fixed the issue for me. Thanks for corroborating that it might be a `dotenv` issue.
https://github.com/bkeepers/dotenv/pull/489/files

**Comment by mhenrixon** [comment]
This has now been fixed in logging.

**Comment by zormandi-byborg** [comment]
Thanks for the update. 👍
